import Footer from "../src/components/Footer";
import Head from "next/head";
export default function category() {
  return (
    <>
    <Head>
        <title>Category</title>
      <meta name="description" content="Generated by create next app" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="theme-color" content="#202020" />
		<meta name="msapplication-navbutton-color" content="#202020" />
		<meta name="apple-mobile-web-app-status-bar-style" content="#202020" />
	
	
		<meta name="author" content="IT Kuliah Karyawan K2" />
		<meta name="title" content="Sipema Kuliah Karyawan K2" />
		<meta name="description" content="Sipema Kuliah Karyawan K2"/>
		<meta property="og:type" content="website" />
		<meta property="og:url" content="https://sipema.kuliahkaryawan.net" />
		<meta property="og:site_name" content="Sipema Kuliah Karyawan K2" />
		<meta property="og:title" content="Sipema Kuliah Karywan K2" />
		
	    <meta name="robots" content="follow" />
		<meta name="google" content="notranslate" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </Head>
    <Footer/>
    </>
  )
}
