import Head from "next/head";
import Image from "next/image";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import style from "../styles/Home.module.css";
import Link from 'next/link';


export default function Home() {
  return (
    <div className="body">
      <Head>
        <title>CERITA RAKYAT</title>
        <meta name="description" content="Generated by create next app" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="theme-color" content="#202020" />
		<meta name="msapplication-navbutton-color" content="#202020" />
		<meta name="apple-mobile-web-app-status-bar-style" content="#202020" />
	
	
		<meta name="author" content="IT Kuliah Karyawan K2" />
		<meta name="title" content="Sipema Kuliah Karyawan K2" />
		<meta name="description" content="Sipema Kuliah Karyawan K2"/>
		<meta property="og:type" content="website" />
		<meta property="og:url" content="https://sipema.kuliahkaryawan.net" />
		<meta property="og:site_name" content="Sipema Kuliah Karyawan K2" />
		<meta property="og:title" content="Sipema Kuliah Karywan K2" />
		
	    <meta name="robots" content="follow" />
		<meta name="google" content="notranslate" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </Head>
      <Header />

      <div className="main">
        <div className="categories section-wrapper">
          <div className="flex-header">
            <h2>Categories</h2>
            <Link href="/kategori">See all</Link>
          </div>
          {/* START KATEGORI */}
          <div className="items">
            <div className="item">
              <div className="item-img">
                <Image
                  className="item-img"
                  src="/assets/img/veg.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
              <h4>Vegetables</h4>
            </div>
            <div className="item">
              <div className="item-img">
                <Image
                  className="item-img"
                  src="/assets/img/veg.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
              <h4>Vegetables</h4>
            </div>
            <div className="item">
              <div className="item-img">
                <Image
                  className="item-img"
                  src="/assets/img/veg.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
              <h4>Vegetables</h4>
            </div>
            <div className="item">
              <div className="item-img">
                <Image
                  className="item-img"
                  src="/assets/img/veg.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
              <h4>Vegetables</h4>
            </div>
            <div className="item">
              <div className="item-img">
                <Image
                  className="item-img"
                  src="/assets/img/veg.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
              <h4>Vegetables</h4>
            </div>
          </div>
          {/* END KATEGORI */}
        </div>
        <div className="promo">
          <div className="items promo-items">
            <div className="promo-item">
              <Image
                className="promo-img"
                src="/assets/img/apples.png"
                alt="me"
                width="100%"
                height="100%"
              />
              <div className="promo-info">
                <h3>30% Discount</h3>
                <p>Order any food from app and get discount</p>
                {/* <a href="">Order now</a> */}
              </div>
            </div>
            <div className="promo-item">
              <Image
                className="promo-img"
                src="/assets/img/banana.png"
                alt="me"
                width="100%"
                height="100%"
              />
              <div className="promo-info">
                <h3>30% Discount</h3>
                <p>Order any food from app and get discount</p>
                <a href="">Order now</a>
              </div>
            </div>
          </div>
        </div>

        {/* STAR POPULAR */}
        <div className="popular section-wrapper">
          <div className="flex-header">
            <h2>Popular deals</h2>
            <Link href="">See all</Link>
          </div>
          <div className="items">
            <div className="popular-item">
              <div className="popular-img">
                <Image
                  className="popular-img"
                  src="/assets/img/1.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
            </div>
            <div className="popular-item">
              <div className="popular-img">
                <Image
                  className="popular-img"
                  src="/assets/img/2.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
            </div>
            <div className="popular-item">
              <div className="popular-img">
                <Image
                  className="popular-img"
                  src="/assets/img/3.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
            </div>
            <div className="popular-item">
              <div className="popular-img">
                <Image
                  className="popular-img"
                  src="/assets/img/4.jpeg"
                  alt="me"
                  width="100%"
                  height="100%"
                />
              </div>
            </div>
          </div>
        </div>
        {/* END POPULAR */}
      </div>
      <Footer />
    </div>
  );
}
