import Footer from "../src/components/Footer";
import Head from "next/head";
import Image from "next/image";

import Link from 'next/link';

export default function information() {
  return (
    <>
    <Head>
        <title>Information</title>
      <meta name="description" content="Generated by create next app" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="theme-color" content="#202020" />
		<meta name="msapplication-navbutton-color" content="#202020" />
		<meta name="apple-mobile-web-app-status-bar-style" content="#202020" />
	
	
		<meta name="author" content="IT Kuliah Karyawan K2" />
		<meta name="title" content="Sipema Kuliah Karyawan K2" />
		<meta name="description" content="Sipema Kuliah Karyawan K2"/>
		<meta property="og:type" content="website" />
		<meta property="og:url" content="https://sipema.kuliahkaryawan.net" />
		<meta property="og:site_name" content="Sipema Kuliah Karyawan K2" />
		<meta property="og:title" content="Sipema Kuliah Karywan K2" />
		
	    <meta name="robots" content="follow" />
		<meta name="google" content="notranslate" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </Head>


      <div className="product-header">
        <div className="flex">
            <Link href="/"><p><span className="las la-angle-left"></span></p></Link>
        </div>
        <div className="product-img">
        
        </div>
    </div>
    
    <div className="main">
    {/* <div className="product-details section-wrapper">
            <h2>Strawberry</h2>
            <small>$17.00/kg</small>
            <div className="details">
                <div>
                    $17.20
                </div>
                <div>
                    14 Calories
                </div>
                <div>
                    <span className="las la-star"></span>
                    4.5(257)
                </div>
            </div>
            <div className="actions">
                <button>
                    <span className="las la-minus"></span>
                </button>
               <input type="text" value={"4 KG"}></input>
                <button>
                    <span className="las la-plus"></span>
                </button>
            </div>
        </div> */}
        
        <div className="product-desc section-wrapper">
            <div className="flex">
                <h3>Information Web Apps</h3>
            </div>
            <div className="description">
                <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century</p>
                <ul>
                    <li>Provides more vitamins than Orange</li>
                    <li>High levels of antioxidants</li>
                </ul>
            </div>
        </div>
        
        {/* <div className="products-wrapper section-wrapper">
            <div className="flex-header">
                <h2>Similar products</h2>
                <a href="products.html">See all</a>
            </div>
            <div className="products">
                <div className="product">
                    <div className="prod-img" ></div>
                    <h3 className="prod-title">Apples</h3>
                    <small>$17.00/kg</small>
                    <h4 className="prod-price">$17.00</h4>
                    
                    <button className="to-cart-btn">
                        <span className="las la-plus"></span>
                    </button>
                </div>
                <div className="product">
                    <div className="prod-img" ></div>
                    <h3 className="prod-title">Banana</h3>
                    <small>$17.00/kg</small>
                    <h4 className="prod-price">$17.00</h4>
                    
                    <button class="to-cart-btn">
                        <span class="las la-plus"></span>
                    </button>
                </div>
                <div className="product">
                    <div className="prod-img" ></div>
                    <h3 className="prod-title">Strawberry</h3>
                    <small>$17.00/kg</small>
                    <h4 className="prod-price">$17.00</h4>
                    
                    <button className="to-cart-btn">
                        <span className="las la-plus"></span>
                    </button>
                </div>
                <div className="product">
                    <div className="prod-img" ></div>
                    <h3 className="prod-title">Orange</h3>
                    <small>$17.00/kg</small>
                    <h4 class="prod-price">$17.00</h4>
                    
                    <button className="to-cart-btn">
                        <span className="las la-plus"></span>
                    </button>
                </div>
            </div>
        </div> */}

    </div>
    
    <Footer/>
    </>
  )
}
