import Footer from "../src/components/Footer";
import Head from "next/head";
export default function story() {
  return (
    <>
    <Head>
        <title>Story </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </Head>
    <Footer/>
    </>
  )
}
